// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: contract/app/app1.proto

package app1

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "base/resp"
	_ "github.com/oaago/go-proto-validators"
	regexp "regexp"
	github_com_oaago_go_proto_validators "github.com/oaago/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *InnerMessage) Validate() error {
	if !(this.SomeInteger > 0) {
		return github_com_oaago_go_proto_validators.FieldError("SomeInteger", fmt.Errorf(`自定义错误`))
	}
	if !(this.SomeInteger < 100) {
		return github_com_oaago_go_proto_validators.FieldError("SomeInteger", fmt.Errorf(`自定义错误`))
	}
	if !(this.SomeFloat >= 0) {
		return github_com_oaago_go_proto_validators.FieldError("SomeFloat", fmt.Errorf(`value '%v' must be greater than or equal to '0'`, this.SomeFloat))
	}
	if !(this.SomeFloat <= 1) {
		return github_com_oaago_go_proto_validators.FieldError("SomeFloat", fmt.Errorf(`value '%v' must be lower than or equal to '1'`, this.SomeFloat))
	}
	return nil
}

var _regex_OuterMessage_ImportantString = regexp.MustCompile(`^[a-z0-9]{5,30}$`)

func (this *OuterMessage) Validate() error {
	if !_regex_OuterMessage_ImportantString.MatchString(this.ImportantString) {
		return github_com_oaago_go_proto_validators.FieldError("ImportantString", fmt.Errorf(`value '%v' must be a string conforming to regex "^[a-z0-9]{5,30}$"`, this.ImportantString))
	}
	if nil == this.Inner {
		return github_com_oaago_go_proto_validators.FieldError("Inner", fmt.Errorf("message must exist"))
	}
	if this.Inner != nil {
		if err := github_com_oaago_go_proto_validators.CallValidatorIfExists(this.Inner); err != nil {
			return github_com_oaago_go_proto_validators.FieldError("Inner", err)
		}
	}
	return nil
}

var _regex_CccDddRequest_Name = regexp.MustCompile(`^[A-Za-z]+$`)

func (this *CccDddRequest) Validate() error {
	if !_regex_CccDddRequest_Name.MatchString(this.Name) {
		return github_com_oaago_go_proto_validators.FieldError("Name", fmt.Errorf(`value '%v' must be a string conforming to regex "^[A-Za-z]+$"`, this.Name))
	}
	if !(this.Age > 0) {
		return github_com_oaago_go_proto_validators.FieldError("Age", fmt.Errorf(`年龄大于0 小于100`))
	}
	if !(this.Age < 100) {
		return github_com_oaago_go_proto_validators.FieldError("Age", fmt.Errorf(`年龄大于0 小于100`))
	}
	return nil
}

var _regex_CccDddReply_Message = regexp.MustCompile(`^[A-Za-z]+$`)

func (this *CccDddReply) Validate() error {
	if !_regex_CccDddReply_Message.MatchString(this.Message) {
		return github_com_oaago_go_proto_validators.FieldError("Message", fmt.Errorf(`value '%v' must be a string conforming to regex "^[A-Za-z]+$"`, this.Message))
	}
	if this.Data != nil {
		if err := github_com_oaago_go_proto_validators.CallValidatorIfExists(this.Data); err != nil {
			return github_com_oaago_go_proto_validators.FieldError("Data", err)
		}
	}
	return nil
}
