// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: app/app.proto

package app

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *GetArticlesReq) Validate() error {
	return nil
}
func (this *GetArticlesResp) Validate() error {
	for _, item := range this.Articles {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Articles", err)
			}
		}
	}
	return nil
}
func (this *Article) Validate() error {
	return nil
}
